import { CardComponent } from '../components/Card';
import Head from 'next/head';
import type { NextPage } from 'next';
import { useState } from 'react';

const Home: NextPage = () => {
  const [isMasked, toggleIsMasked] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main id='app'>
        <div
          onMouseOver={() => toggleIsMasked(false)}
          onMouseLeave={() => toggleIsMasked(true)}
        >
          <CardComponent
            cvv='109'
            number='4124214091289090'
            expiry='07/25'
            fullName='Ernelus Satia'
            isMasked={isMasked}
            logoUrl='/heartykitchens.svg'
            providerLogo='/Visa.svg'
          />
        </div>
      </main>
    </>
  );
};

export default Home;
