import { Card } from '../components/Card';
import Head from 'next/head';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main id='app'>
        <Card
          expiry='07/25'
          cvv='109'
          fullName='Ernelus Satia'
          logoUrl='/heartykitchens.svg'
          providerLogo='/Visa.svg'
        />
      </main>
    </>
  );
};

export default Home;
